name: Generate images.json

on:
  push:
    paths:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - 'generate_images_json.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run JSON generation script
      run: python generate_images_json.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update images.json files [skip ci]"
        git push
